Repository facebook/fbt, pull requests merged in 2019-11, with the labels that each got.

#106 Re-sync with internal repository
  package.json
  yarn.lock
Labels: CLA Signed, fh:direct-merge-enabled

#107 Re-sync with internal repository
  jest/assets.js
  jest/css.js
  jest/setup.js
  src/example/Example.react.js
  src/example/__tests__/Example.react-test.js
  src/root.js
  webpack.config.js
Labels: CLA Signed

#112 Fix sync issue between FB repo and GitHub
  flow-types/libdef/fbt.js
  flow-types/typed-js-modules/NumberFormatConfig.js.flow
  runtime/shared_deps
  runtime/shared_deps/DisplayGenderConst.js
Labels: CLA Signed, bug
